"""
URL mappings for the recipe app.
"""
from django.urls import (
    path,
    include,
)

# DefaultRouter used as a API view to automatically create router
# for all the options in the view
from rest_framework.routers import DefaultRouter
from recipe import views

router = DefaultRouter()

# register the viewset with the router,create a new endpoint named /recipes and assign all the different
# endpoints from the recipe view set to that endpoint, can do all CURD
#  through this endpoint, the rescipe viewset will have auto
# generated urls depending on the functionality enabled on the viewsets
# it is supporting all the operations delete, read, update, so
# will create and register endpoint for each of these options
router.register('recipes', views.RecipeViewSet)
router.register('tags', views.TagViewSet)
router.register('ingredients', views.IngredientViewSet)


app_name = 'recipe'


# get the url registered by router, finally need to wire up with the main
#  url in app/urls
#  include the urls generated by the router
urlpatterns = [
    path('', include(router.urls)),
]